spring.application.name=ApiGateway
server.port=6004
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.client.fetchRegistry=true
eureka.client.registerWithEureka=true
spring.main.web-application-type=reactive

spring.cloud.gateway.routes[0].id=Student-Service
#spring.cloud.gateway.routes[0].uri=lb://Student-Service
spring.cloud.gateway.routes[0].uri=http://localhost:6002/
spring.cloud.gateway.routes[0].predicates[0]=Path=/student/**

spring.cloud.gateway.routes[1].id=Course-Service
#spring.cloud.gateway.routes[1].uri=http://Course-Service
spring.cloud.gateway.routes[1].uri=http://localhost:6003/
spring.cloud.gateway.routes[1].predicates[0]=Path=/course/**

#spring.cloud.gateway.routes[0].id=user-service
#spring.cloud.gateway.routes[0].uri=lb://user-service
#spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**

#spring.cloud.gateway.routes[1].id=notf-service
#spring.cloud.gateway.routes[1].uri=lb://notf-service
#spring.cloud.gateway.routes[1].predicates[0]=Path=/notif/**

#spring.cloud.gateway.routes[2].id=post-service
#spring.cloud.gateway.routes[2].uri=lb://post-service
#spring.cloud.gateway.routes[2].predicates[0]=Path=/post/**


#spring.main.web-application-type=reactive
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
#spring.cloud.gateway.routes[0].id=account-status-check
#spring.cloud.gateway.routes[0].uri=lb://AccountMgmt
#spring.cloud.gateway.routes[0].predicates[0]=Path=/account/check
#spring.cloud.gateway.routes[0].predicates[1]=Method=GET
#spring.cloud.gateway.routes[0].filters[0]=RemoveRequestHeader=Cookie
#spring.cloud.gateway.routes[0].filters[1]=RewritePath=/sk/account/check, /account/check
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true
