spring.application.name=EurekaRegistery
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

logging.file.name=C:/Java_Code/MicroServices_Tracing_Resilience4J_Spring_Sleuth/logs/applog.txt

#eureka.client.registerWithEureka=false
#eureka.client.fetchRegistry=false

#eureka.client.service-url.defaultZone=http://localhost:6007/eureka